.travis.yml, cmake/CodeCoverage.cmake, test/CMakeLists.txt, test/api/one/one_blocks.cpp, test/api/two/two_transactions.cpp, travis/script_desktop.sh
Added support for Travis CI to run code coverage
and upload the report to CodeCov.
Fixes #4
=> feat: add codecov support

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Added github issue and PR templates.
FIles pulled from https://github.com/ArkEcosystem/boilerplate
Fixes #2
=> chore: Add github templates

include/stl/array, include/stl/cassert, include/stl/cctype, include/stl/cstddef, include/stl/cstdint, include/stl/cstdio, include/stl/cstring, include/stl/details/to_string.h, include/stl/memory, src/api/one/blocks/one_blocks.cpp, src/api/one/delegates/one_delegates.cpp, src/api/one/peers/one_peers.cpp, src/api/one/transactions/one_transactions.cpp, src/api/two/blocks/two_blocks.cpp, src/api/two/delegates/two_delegates.cpp, src/api/two/peers/two_peers.cpp, src/api/two/transactions/two_transactions.cpp, src/api/two/votes/two_votes.cpp, src/api/two/wallets/two_wallets.cpp, src/helpers/helpers.h, test/api/one/one_loader.cpp, test/api/one/one_peers.cpp, test/api/one/one_transactions.cpp, test/api/two/two_blocks.cpp, test/api/two/two_delegates.cpp, test/api/two/two_peers.cpp, test/api/two/two_wallets.cpp
Replaced custom ToString function with STL std::to_string.  Added std::to_string implementations to support platforms that do not have it (yet).
Added additional STL implementations from previous work to match Cpp-Crypto and to have available going forward.
Fixes #11
=> feat: Refactor ToString

src/api/api_base.h, src/api/one/accounts/one_accounts.cpp, src/api/one/accounts/one_accounts.h, src/api/one/blocks/one_blocks.cpp, src/api/one/blocks/one_blocks.h, src/api/one/delegates/one_delegates.cpp, src/api/one/delegates/one_delegates.h, src/api/one/loader/one_loader.cpp, src/api/one/loader/one_loader.h, src/api/one/peers/one_peers.cpp, src/api/one/peers/one_peers.h, src/api/one/signatures/one_signatures.cpp, src/api/one/signatures/one_signatures.h, src/api/one/transactions/one_transactions.cpp, src/api/one/transactions/one_transactions.h, test/iot/gtest/gtest.h
Clean up v1 API code
- Replaced strcpy/strcat with snprintf to provide buffer overflow protection and reduce string copies from int to string conversions.
- Corrected spacing to match .editorconfig
- Applied C++11-isms 
N/A
=> chore: Clean up v1 API code

src/api/one/one_api.h, src/api/one/one_paths.h, src/api/two/blocks/two_blocks.cpp, src/api/two/blocks/two_blocks.h, src/api/two/delegates/two_delegates.cpp, src/api/two/delegates/two_delegates.h, src/api/two/node/two_node.cpp, src/api/two/node/two_node.h, src/api/two/peers/two_peers.cpp, src/api/two/peers/two_peers.h, src/api/two/transactions/two_transactions.cpp, src/api/two/transactions/two_transactions.h, src/api/two/two_api.h, src/api/two/two_paths.h, src/api/two/votes/two_votes.cpp, src/api/two/votes/two_votes.h, src/api/two/wallets/two_wallets.cpp, src/api/two/wallets/two_wallets.h, src/connection/connection.h, test/api/two/two_node.cpp
Clean up v2 API code
- Replaced strcpy/strcat with snprintf to provide buffer overflow protection and reduce string copies from int to string conversions.
- Corrected spacing to match .editorconfig
- Applied C++11-isms 
- Did further clean up in non-v2 code to remove unnecessary semicolons and const.
N/A
=> chore:  Clean up v2 API code

.codecov.yml, .gitignore
Add a Codecov config file to ignore tests when calculating code coverage.  There is IoT test code that is not executed on desktops and skews the coverage numbers.
Minor .gitignore cleanup/mods
=> chore: Ignore tests in Codecov

test/iot/gtest/gtest.h
Removed locally defined macro now that proper support has been added to AUnit. 
Updated AUnit library is published to PIO Library manager.
=> chore: Remove locally defined macro

test/api/one/one_accounts.cpp, test/api/one/one_blocks.cpp, test/api/one/one_delegates.cpp, test/api/one/one_peers.cpp, test/api/one/one_transactions.cpp, test/api/two/two_delegates.cpp, test/api/two/two_node.cpp, test/api/two/two_peers.cpp, test/api/two/two_transactions.cpp, test/api/two/two_votes.cpp, test/api/two/two_wallets.cpp
Clean up test code to make better use of available asserts.
Starting to work with AUnit author to provide support for 64 bit integer operations and support for "isNull" concept.  This will allow the testing code be even cleaner.
=> chore:  Clean up assert usage in tests

src/api/two/transactions/two_transactions.cpp, src/include/cpp-client/api/two/transactions/two_transactions.h, test/api/two/two_transactions.cpp
Added the /api/v2/transactions/search function and associated tests.
N/A
=> feat:  Add /api/v2/transactions/search function

README.md, src/api/blocks/blocks.cpp, src/api/transactions/transactions.cpp, src/api/wallets/wallets.cpp, src/include/cpp-client/api/abstract.h, src/include/cpp-client/api/api.h, src/include/cpp-client/api/base.h, src/include/cpp-client/api/blocks/blocks.h, src/include/cpp-client/api/transactions/transactions.h, src/include/cpp-client/api/wallets/wallets.h, src/include/cpp-client/connection/connection.h, test/api/blocks.cpp, test/api/transactions.cpp, test/api/wallets.cpp
Merge the recent changes from `master` into the `develop` branch.
These changes include those from the following PR's:
#36, #37, #38, #40, #41, & #42
=> misc: update develop branch

extras/ARDUINO_IDE.sh
This PR is targeting the 'develop' branch.
Cpp-Client uses an 'include' folder scheme to expose the public interface.
The Arduino IDE does not support this.
This script extends support to the Arduino IDE by moving headers from 'include' into their relative directories in the 'src' folder.
Additionally, once this script has been ran, it can be executed again to undo these changes.
While it would be preferable to find a solution to support the Arduino IDE without the use of a script; this addition will serve as a good-enough fix in the mean time.
=> feat: Add Arduino IDE Script

src/http/iot/http.cpp
Arduino's HTTPClient requires a single-line URL request string begin with "http://".
Absence of "http://" will lead to 'connection refused' errors.
This is a client-side issue and is only a consideration on IoT, so this should not be resolved anywhere else except this header.
This PR adds a 'toHttpStr' method to properly prepend an HTTP request string with "https://".
=> fix: Arduino HTTP Request String

src/http/iot/http.cpp, src/http/os/http.cpp
https://github.com/ArkEcosystem/core/pull/1970
=> fix: use the correct API version header

test/CMakeLists.txt, test/http/http.cpp
This PR adds tests for the HTTP interface using a live on-network peer.
- Test 'get'
- Test 'post'
- Test requests strings
- Test default/unset 'api_version'
The need for this was also discussed in #57
=> test: http interface

library.json, library.properties
Update library information per @kristjank .
These changes will be reflected in external package/library managers.
This PR updates authorship and descriptive content.
=> chore: update library info

library.properties, platformio.ini
Fixes failing Arduino IDE library import.
- add missing 'maintainer' tag.
- also update PlatformIO description.
=> fix: library info

src/helpers/client_helpers.h, src/http/iot/http.cpp, src/http/iot/main.cpp, src/http/os/http.cpp
Cpp-Client uses the header 'helpers/helpers.h'.
Cpp-Crypto also uses this 'helpers/helpers.h' naming.
These headers are not identical and contain only “helper” functions specific to its library.
When both Cpp-Client & Cpp-Crypto are included in the same project, it results in one of the headers being dropped.
This PR renames 'helpers/helpers.h' to 'helpers/client_helpers.h’, and resolves the issue.
There will also be a PR in ArkEcosystem/Cpp-Crypto to match this revised naming.
=> fix: rename helpers

test/api/node.cpp
Missing comment closure resulted in skipped test.
This PR adds the missing closure to resolve this issue.
=> fix: Node Tests

src/api/paths.cpp, src/api/transactions/transactions.cpp, src/http/iot/http.cpp, src/http/os/http.cpp, src/include/cpp-client/api/paths.h, src/include/cpp-client/api/transactions/transactions.h, test/api/paths.cpp, test/api/transactions.cpp, test/http/http.cpp, test/mocks/mock_api.h
Cpp-Client does not currently have a method for sending TX's.
This PR does the following:
- adds `Transactions::send()` Paths method.
- adds `Transactions::send()` method.
- adds test for `send` Path method.
- adds mock test for `send` `Transactions` method.
=> feat: TX Send

library.json
This PR primarily adds the Arduino Sketch/Example path to `library.json`.
This allows external package managers to properly list our examples.
It also corrects the `platformio_example` path.
adds to and updates library configuration file
=> misc: add Arduino Sketch path to Library Config

library.json
PlatformIO uses globbing in `library.json` for the 'examples' paths.
> https://docs.platformio.org/en/latest/librarymanager/config.html#examples
This PR drops explicit path naming in favor of the wildcard(**\***) syntax.
This allows SDK examples to be properly displayed in the PIO library manager.
=> fix: library config examples' paths

library.json
This PR removes the following fields from `library.json`:
- "export"
- "examples"
Releases should include all files and folders from the `root/` dir for the source code zip.
Also, Per PIO, the "examples" field not being present defaults to the paths that are already shown. So this part is just redundant.
=> fix: Remove Unneeded/Redundant Manifest Fields

.circleci/config.yml, .circleci/install_arduino.sh, .circleci/script_arduino.sh, library.json
This PR adds the necessary configuration for CircleCI to compile the Cpp-Client library via Arduino-CLI. If the Cpp-Client library builds successfully via Arduino-CLI, the test is considered to have passed.
At this time, only the ESP32 chipset is supported in this test.
**note:** _CI will fail until #72  is merged, and this PR is updated._
Reasons for this change:
- Promote Arduino IDE compatibility.
- Improve maintainability of an incoming `Arduino` branch for the Arduino IDE Library Manager src.
=> test: Add Arduino CircleCI Config

examples/arduino/ESP32/ESP32.ino, examples/arduino/ESP8266/ESP8266.ino
I found and fixed some typos and misspellings in this repository.
=> Fixed misspellings

CHANGELOG.md, src/host/host.cpp, src/include/cpp-client/host/host.h, test/api/paths.cpp, test/connection/connection.cpp, test/host/host.cpp, test/http/http.cpp
This PR primarily deals with improving test coverage.
Specifically, this PR does the following:
- removes unnecessary methods in `host` class.
- uses string instead of char* in `Host::ip`.
- improves testing of `host` class.
- improves testing of `paths` class.
- updates connection test to use string.
- improves testing of `host` class.
- updates the change log.
Improves class members and test coverage to 100%.
=> test: increase coverage

library.json
This PR updates the dependencies list in the library.json manifest.
Just helps keep the manifests stay consistent across branches and repos.
It shouldn't really affect much otherwise.
~- [ ] New/updated tests are included~ n/a
=> chore(manifest): add supported platforms arduino

.gitignore, .vscode/settings.json, .vscode/tasks.json, CMakeLists.txt
Added support for VS Code line by line debugging
Added support for building from VS Code IDE
Added support for GTest extension within VS Code
This ultimately adds easy line by line debugging support for
Windows, Mac, and Linux.
=> feat: Add debug support for VS Code

.github/workflows/test.yml
Environment variables aren't persisted between steps so they need to be set per step or globally.
=> ci: pass environment variables to steps

test/platformio.ini
This PR changes the PIO configs to use explicit package versions.
=> chore(pio): use explicit package version

.codeclimate.yml
C++ isn't supported out of the box but requires a plugin to be configured. See https://docs.codeclimate.com/docs/cppcheck and https://github.com/antiagainst/codeclimate-cppcheck#configuration.
=> ci: setup cppcheck for codeclimate

test/iot/test_main.cpp, test/platformio.ini
Split up and re-enabled ESP8266 tests.  API tests required further
splitting due to large amounts of strings.
Requires #157 and a rebase, or close #157 and just merge this PR.  However you want to break it up.
=> Enable esp8266 tests

test/iot/platform.hpp, test/iot/test_main.cpp, test/platformio.ini
* Disabled WiFi  radio during tests to lower current  draw.
* Increased CPU frequency to execute tests faster to improve
stability.
Also removed debug code that got left in for upload_port.
=> feat: disable wifi on esp8266 during tests

CHANGELOG.md
- Separate Changelogs by platform.
eg
`tree/master`
- \#\# [1.4.0] - 2020-02-13
`tree/arduino`
- \#\# [1.4.0-arduino] - 2020-02-13
=> docs(changelog): separate platforms [arduino]

src/api/paths.cpp, test/api/paths.cpp
- add test for `Paths::Node::fees`.
- add static method to join body parameters.
(replaced pattern was used 6 times; half missed in tests)
This brings coverage back to 100%.
=> ci(cov): add/hit missing tests 

.codacy.yml, .github/workflows/test/clang_format.sh, .github/workflows/test/clang_tidy.sh, .github/workflows/test/install_platform_io.sh, .github/workflows/test/script_desktop.sh, .github/workflows/test/script_platform_io.sh, build.sh, run_tests.sh, test/iot/platform.hpp
Improvements per Codacy and Codefactor
- rm `codacy.yml` config file.
- not used by repo/org, configuration allowed via codacy dashboard.
- update all `.sh` files to use the `#!/usr/bin/env bash` shebang.
- rm duplicate empty lines in `test/iot/platform.hpp` file.
=> ci: maintenance

src/api/blocks/blocks.cpp, src/api/paths.cpp, src/include/cpp-client/api/blocks/blocks.h, src/include/cpp-client/api/paths.h, test/api/blocks.cpp, test/api/paths.cpp, test/mocks/mock_api.h
Adds methods for the `blocks/first` and `blocks/last` endpoints.
=> feat: add methods for first and last block

src/api/blocks/blocks.cpp, src/api/blocks/blocks.h, src/api/paths.cpp, src/api/paths.h
Matches changes in https://github.com/ArkEcosystem/cpp-client/pull/183
>Adds methods for the `blocks/first` and `blocks/last` endpoints.
=> feat: add methods for first and last block [arduino]

CHANGELOG.md, library.json, library.properties
-   Added First and Last Block methods [#185]
=> release: 1.4.1 [arduino]

examples/arduino/ESP32/ESP32.ino, examples/arduino/ESP8266/ESP8266.ino, test/api/node.cpp
=> chore: replaced dexplorer occurences with dwallets
