ArkEcosystem/cpp-client

.circleci/clang_format.sh
.circleci/config.yml
.clang_format

Added support for running clang format in CI.  clang format warnings will not error the build (yet?)
N/A

chore: add clang format support

---

docs/cpp.md
examples/platformio_example/src/main.ino
test/api/blocks.cpp
test/api/delegates.cpp
test/api/node.cpp
test/api/peers.cpp
test/api/transactions.cpp
test/api/votes.cpp
test/api/wallets.cpp

This PR removes references to "two" pertaining to the API version.
There's no reason to reference the distinction of "two" for API naming anymore.
These "two" references were mostly in test method names, as well as a reference in 'docs/cpp.md'.
They snuck through during the V1 drop.

fix: remove "two" references

---

extras/ARDUINO_IDE.sh
library.json

This PR modifies the `extras/ARDUINO_IDE.sh` script to allow the passing of `--auto` to skip interface prompts.
This is primarily an improvement to aid CI and Arduino releases.

chore: Automate Arduino Script

---

keywords.txt

The Arduino IDE requires the use of a single true tab separator between the keyword name and identifier. When spaces are used rather than a true tab, the keyword is not highlighted.
Reference:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#keywords
- [NA] All tests are passing
- [NA] New/updated tests are included
- [NA] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

chore: use correct field separator in keywords.txt

---

library.json

As reported by @yhyuan in https://github.com/ArkEcosystem/cpp-crypto/issues/104,
the current library manifest uses a wildcard `*` for the `platforms` value signifying that it supports all platforms.
This is incorrect as the Cpp SDK's only officially support the espressif8266 & espressif32 platforms.  This PR corrects that discrepancy.
Affects external package manager library manifest
- [n/a] New/updated tests are included

fix(manifest): Correct Supported Platforms

---

src/include/cpp-client/api/abstract.h
src/include/cpp-client/http/http.h
test/http/http.cpp
test/mocks/mock_api.h
test/mocks/mock_http.h

Fixes remaining changes from `refactor/legacy` in #100 .
Specifically,
- [abstract.h]
- `explicit` keyword moved to single argument constructor.
> per: https://google.github.io/styleguide/cppguide.html#Implicit_Conversions
- [http.h]
- added default constructor;
- changed copy assignment operator to default.
- [test/mock_api.h]
- removed legacy version-value from constructor.
- [test/mock_http.h]
- removed default `MockHTTP()` constructor (now unneeded).
- [test/http.h]
- fixes to make tests pass with current devnet core.
- future PR should be done to use some other source.
~- [ ] It's submitted to the `develop` branch, _not_ the `master` branch~ n/a
~- [n/a ] New/updated tests are included~ n/a

fix: refactor legacy

---

docs/cpp.md
examples/arduino/ESP32/ESP32.ino
examples/arduino/ESP8266/ESP8266.ino
examples/cmake_example/main.cpp
examples/platformio_example/src/main.ino
src/http/iot/http.cpp
src/http/os/http.cpp
src/include/cpp-client/api/abstract.h
src/include/cpp-client/api/api.h
src/include/cpp-client/http/http.h
test/api/blocks.cpp
test/api/delegates.cpp
test/api/node.cpp
test/api/peers.cpp
test/api/transactions.cpp
test/api/votes.cpp
test/api/wallets.cpp
test/connection/connection.cpp
test/http/http.cpp
test/mocks/mock_api.h
test/mocks/mock_http.h

Remove all code that related to setting an API-Version as Core 2.5 will only serve the v2 API.

refactor: remove version argument remains

---

src/http/iot/http.cpp
src/http/os/http.cpp

Always send the `Content-Type: application/json` header for all HTTP verbs instead of performing a traditional form post for `POST` requests.

fix: always send application/json as content-type

---

test/api/paths.cpp

Should bring coverage back up to 100%

test(blockchain): add missing paths test

---

CHANGELOG.md
docs/cpp.md
examples/arduino/ESP32/ESP32.ino
examples/arduino/ESP8266/ESP8266.ino
src/api/blocks/blocks.cpp
src/api/delegates/delegates.cpp
src/api/paths.cpp
src/api/peers/peers.cpp
src/api/transactions/transactions.cpp
src/api/votes/votes.cpp
src/api/wallets/wallets.cpp
src/include/cpp-client/api/blocks/blocks.h
src/include/cpp-client/api/delegates/delegates.h
src/include/cpp-client/api/paths.h
src/include/cpp-client/api/peers/peers.h
src/include/cpp-client/api/transactions/transactions.h
src/include/cpp-client/api/votes/votes.h
src/include/cpp-client/api/wallets/wallets.h
test/api/blocks.cpp
test/api/delegates.cpp
test/api/paths.cpp
test/api/peers.cpp
test/api/transactions.cpp
test/api/votes.cpp
test/api/wallets.cpp
test/mocks/mock_api.h

API queries were previously limited to `limit` and `page`.
This PR basically just changes the API query arguments to be accepted as a string.
This PR also does the following:
- updates all tests.
- updates documentation to reflect changes.
- updates changelog.
There will be several more updates before merge to master and a new version release.

chore: improve API query usage.

---

.appveyor
.appveyor.yml

chore: Add appveyor support

---

src/api/node/node.cpp
src/api/paths.cpp
src/include/cpp-client/api/node/node.h
src/include/cpp-client/api/paths.h
test/api/node.cpp
test/api/paths.cpp
test/mocks/mock_api.h

Adds the `node/configuration/crypto` endpoint.

feat: crypto endpoint

---

CMakeSettings.json

Added support for VS2019 and maintained support for VS2017.

chore:  Add support for VS2019

---

extras/ARDUINO_IDE.sh
src/CMakeLists.txt
src/api/node/node.cpp
src/api/paths.cpp
src/api/rounds/rounds.cpp
src/api/transactions/transactions.cpp
src/include/cpp-client/api/api.h
src/include/cpp-client/api/node/node.h
src/include/cpp-client/api/paths.h
src/include/cpp-client/api/rounds/rounds.h
src/include/cpp-client/api/transactions/transactions.h
test/CMakeLists.txt
test/api/blocks.cpp
test/api/node.cpp
test/api/paths.cpp
test/api/rounds.cpp
test/api/transactions.cpp
test/mocks/mock_api.h

Adds the `rounds` API endpoints.
Adds the `transaction/fees` endpoint.
Adds the `node/fees` endpoint.

feat: add missing api endpoints

---

.github/workflows/test.yml
.github/workflows/test/script_arduino.sh

This PR adjusts the Arduino CI paths for GH Actions.

ci: update arduino triggers

---

cmake/extern/CURL.txt.in
cmake/extern/GTest.txt.in

This PR adds project-download calls to silence external package build warnings.

fix: cmake warnings

---

.codecov.yml

Mocked API show 0% coverage even though they're all tested.
This PR hides mocked API and other unused folders from coverage reports.
The `Paths`, `Connection`, `Host`, and `HTTP` classes are reported correctly.
A subsequent PR should address refactoring for testability and accurate coverage reports.

ci: hide mocked api coverage

---

.github/workflows/codeclimate.yml
.github/workflows/coverage.yml

As in the C++ Crypto repo, CodeClimate Coverage attempts to use the CC_TEST_REPORTER_ID of the PR base for reporting on the upstream parent and fails.
This PR splits workflows so that CodeClimate Coverage onlys runs on Pushes to master/devleop.
CodeCov will continue to run on PR's and Pushes.

ci: split coverage workflows

---

test/platformio.ini

ESP32 test builds were not passing and the tests themselves were not
being compiled into the firmware binary.  Added missing ignore filters
to ignore desktop libraries for building PIO and desktop targets in the
same source tree.

Fix ESP32 Tests

---

.github/workflows/test/install_arduino.sh
.github/workflows/test/script_arduino.sh

With the recent support for esp8266 added back in, it would be nice to have that in the Arduino CLI CI tests.

ci: add esp8266 arduino cli configs back

---

cmake/extern/CURL.txt.in
cmake/extern/GTest.txt.in

- ignores detached head warnings when cloning external libs via CMake.

build: hide cmake warning

---

README.md

- add [![C++11](https://badgen.net/badge/c++/11/blue?labelColor=black)](https://isocpp.org/wiki/faq/cpp11) to `README.md` badges.

chore(docs): add c++11 badge

---

src/api/paths.cpp

The pattern to join bodies of an API query is used 6 times in the `paths.cpp` file.
This PR extracts a static method, matching the same change in https://github.com/ArkEcosystem/cpp-client/pull/180.

chore(paths): extract query pattern [arduino]

---

test/platformio.ini

Looks like PlatformIO stopped using their staging branch for ESP8266 firmware, which started causing build errors.
Changing the test PIO config to pull from their master branch resolves this issue.

test(pio): fix esp8266 platform urls

---

CHANGELOG.md
examples/arduino/ESP32/ESP32.ino
examples/arduino/ESP8266/ESP8266.ino
src/host/host.cpp
src/http/iot/http.cpp
src/http/os/http.cpp
test/http/http.cpp

Add Https support for OS and IoT builds. 
- '**host.cpp**': add support for url prefixes (http(s)://)\<address>:\<port>.
- '**http.cpp**': refactor and add support for Https.
- '**test/http**': update tests to reflect changes.
- update arduino examples.
- update CHANGELOG.
This resolves #191 & #192

feat: support https

---

CHANGELOG.md
examples/ESP32/ESP32.ino
examples/ESP8266/ESP8266.ino
src/host/host.cpp
src/http/http.cpp

Add Https support for Arduino. 
- '**host.cpp**': add support for url prefixes (http(s)://)\<address>:\<port>.
- '**http.cpp**': refactor and add support for Https.
- update arduino examples.
- update CHANGELOG.

feat: support https [arduino]
